/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GribMessage {
  static parseFromBuffer(buffer: Uint8Array, offset: number): GribMessage
  get key(): string
  get varName(): string
  get varAbbrev(): string
  get units(): string
  get forecastDate(): Date
  get referenceDate(): Date
  get forecastEndDate(): Date | null
  get proj(): string
  get crs(): string
  get gridShape(): GridShape
  get latlng(): LatLng
  /**
   * Like the `latlng` getter, but when `adjustLongitudeRange` is set the
   * longitudes of an eligible near-global grid are wrapped from `[0, 360)` to a
   * monotonic `[-180, 180)` axis. Pair with `dataAdjusted(true)` so the values
   * stay aligned with the wrapped coordinates. A no-op for grids that don't
   * span the globe (returns the same as `latlng`).
   */
  latlngAdjusted(adjustLongitudeRange: boolean): LatLng
  get isRegularGrid(): boolean
  get hasBitmap(): boolean
  get perturbationNumber(): number | null
  get numberOfEnsembleMembers(): number | null
  get data(): Array<number>
  /**
   * Like the `data` getter, but when `adjustLongitudeRange` is set the decoded
   * values of an eligible near-global grid have their columns rolled to match a
   * `[-180, 180)` longitude axis, staying aligned with `latlngAdjusted(true)`.
   * A no-op for grids that don't span the globe (returns the same as `data`).
   */
  dataAdjusted(adjustLongitudeRange: boolean): Array<number>
}

export declare class GribMessageFactory {
  static fromBuffer(buffer: Uint8Array): GribMessageFactory
  get availableMessages(): Array<string>
  getMessage(key: string): GribMessage
}

export declare class GribMessageMetadataFactory {
  static fromBuffer(buffer: Uint8Array): GribMessageMetadataFactory
  get availableMessages(): Array<string>
  getMessage(key: string): GribMessage
}

/**
 * Wrap a `[0, 360)` longitude coordinate axis to a monotonic `[-180, 180)`
 * range, matching the column roll `dataAdjusted` applies to the values. A
 * no-op for axes that aren't eligible near-global ascending grids (returns the
 * input unchanged), so it is safe to call on any longitude array.
 */
export declare function adjustLongitudeValues(longitudes: Array<number>): Array<number>

/**
 * One entry of a GRIB sidecar index file (NOAA wgrib2 `.idx` or ECMWF
 * open-data `.index`), locating a single message inside a GRIB file. Use the
 * offset/length as an HTTP Range request, then parse the fetched bytes with
 * `GribMessage.parseFromBuffer(bytes, 0)` — no full-file download needed.
 */
export interface GribIndexEntry {
  /** 1-based message number (the line number for ECMWF indexes). */
  messageNumber: number
  /**
   * GRIB2 submessage number for NOAA `msg.submsg` lines; submessages share
   * their parent message's byte range.
   */
  submessage?: number
  /** Byte offset of the message start within the GRIB file. */
  offset: number
  /**
   * Message size in bytes. Explicit in ECMWF indexes; inferred from the next
   * entry's offset in NOAA indexes, so undefined for the final entry unless
   * the GRIB file size is supplied.
   */
  length?: number
  /** Model reference (initialization) time. */
  referenceDate?: Date
  /** Variable identifier: NOAA abbreviation ("TMP") or ECMWF MARS param ("2t"). */
  var?: string
  /** Level, verbatim ("2 m above ground", or ECMWF levelist). */
  level?: string
  /** Forecast time, verbatim ("3 hour fcst", "anl", or ECMWF step). */
  forecastTime?: string
  /** Trailing NOAA fields verbatim ("ENS=+5", probability info, ...). */
  extra: Array<string>
  /** ECMWF MARS keys verbatim (levtype, stream, number, ...). */
  keys: Record<string, string>
}

export interface GridShape {
  rows: number
  cols: number
}

export interface LatLng {
  latitude: Array<number>
  longitude: Array<number>
}

/**
 * Parse a GRIB sidecar index file (NOAA wgrib2 `.idx` or ECMWF open-data
 * `.index`, auto-detected) into entries locating each message. `fileSize`
 * (if known) sizes the final entry of a NOAA index.
 */
export declare function parseGribIndex(data: string, fileSize?: number | undefined | null): Array<GribIndexEntry>

export declare function parseMessagesFromBuffer(buffer: Uint8Array): Array<GribMessage>
