/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class GribMessage {
  static parseFromBuffer(buffer: Uint8Array, offset: number): GribMessage
  get key(): string
  get varName(): string
  get varAbbrev(): string
  get units(): string
  get forecastDate(): Date
  get referenceDate(): Date
  get forecastEndDate(): Date | null
  get proj(): string
  get crs(): string
  get gridShape(): GridShape
  get latlng(): LatLng
  get isRegularGrid(): boolean
  get hasBitmap(): boolean
  get perturbationNumber(): number | null
  get numberOfEnsembleMembers(): number | null
  get data(): Array<number>
}

export declare class GribMessageFactory {
  static fromBuffer(buffer: Uint8Array): GribMessageFactory
  get availableMessages(): Array<string>
  getMessage(key: string): GribMessage
}

export declare class GribMessageMetadataFactory {
  static fromBuffer(buffer: Uint8Array): GribMessageMetadataFactory
  get availableMessages(): Array<string>
  getMessage(key: string): GribMessage
}

export interface GridShape {
  rows: number
  cols: number
}

export interface LatLng {
  latitude: Array<number>
  longitude: Array<number>
}

export declare function parseMessagesFromBuffer(buffer: Uint8Array): Array<GribMessage>
