pub mod product_template;
pub mod tables;
pub mod horizontal_analysis_template;
pub mod average_accumulation_extreme_horizontal_analysis_template;

pub use horizontal_analysis_template::HorizontalAnalysisForecastTemplate;
pub use average_accumulation_extreme_horizontal_analysis_template::AverageAccumulationExtremeHorizontalAnalysisForecastTemplate;