/// ECMWF Table 140 - Wave model parameters
/// (parameter_number, abbreviation, name, units)
pub const ECMWF_TABLE_140: &[(u8, &str, &str, &str)] = &[
    (121, "swh1", "Significant wave height of first swell partition", "m"),
    (122, "mwd1", "Mean wave direction of first swell partition", "degrees"),
    (123, "mwp1", "Mean wave period of first swell partition", "s"),
    (124, "swh2", "Significant wave height of second swell partition", "m"),
    (125, "mwd2", "Mean wave direction of second swell partition", "degrees"),
    (126, "mwp2", "Mean wave period of second swell partition", "s"),
    (127, "swh3", "Significant wave height of third swell partition", "m"),
    (128, "mwd3", "Mean wave direction of third swell partition", "degrees"),
    (129, "mwp3", "Mean wave period of third swell partition", "s"),
    (218, "hmax", "Maximum individual wave height", "m"),
    (220, "mp1", "Mean wave period based on first moment", "s"),
    (221, "mp2", "Mean wave period based on second moment", "s"),
    (222, "wdw", "Wave spectral directional width", ""),
    (223, "p1ww", "Mean wave period based on first moment of wind waves", "s"),
    (224, "p2ww", "Mean wave period based on second moment of wind waves", "s"),
    (225, "dwww", "Wave spectral directional width of wind waves", ""),
    (226, "p1ps", "Mean wave period based on first moment of swell", "s"),
    (227, "p2ps", "Mean wave period based on second moment of swell", "s"),
    (228, "dwps", "Wave spectral directional width of swell", ""),
    (229, "swh", "Significant height of combined wind waves and swell", "m"),
    (230, "mwd", "Mean wave direction", "degrees"),
    (231, "pp1d", "Peak wave period", "s"),
    (232, "mwp", "Mean wave period", "s"),
    (233, "cdww", "Coefficient of drag with waves", ""),
    (234, "shww", "Significant height of wind waves", "m"),
    (235, "mdww", "Mean direction of wind waves", "degrees"),
    (236, "mpww", "Mean period of wind waves", "s"),
    (237, "shts", "Significant height of total swell", "m"),
    (238, "mdts", "Mean direction of total swell", "degrees"),
    (239, "mpts", "Mean period of total swell", "s"),
    (244, "msqs", "Mean square slope of waves", "dimensionless"),
    (245, "wind", "10 metre wind speed", "m s-1"),
    (249, "aif", "Air density over the oceans", "kg m-3"),
    (251, "strd2", "Surface net thermal radiation", "J m-2"),
    (252, "ssrd2", "Surface net solar radiation", "J m-2"),
];
